### ISSUE TITLE
What happened to v2.0.1?

### ISSUE THREAD

**Issue by marwan-at-work** [gobuffalo/uuid#4]
Did https://github.com/gobuffalo/uuid/tags ever have a v2.0.1 or did it get jumped? The Athens Gopkg.lock (https://github.com/gomods/athens/blob/e2cd124816b1075e558d095a7779863552397866/Gopkg.lock#L262) points to v2.0.1 but it doesn’t seem to exist https://github.com/gobuffalo/uuid/tags

Thanks :)

**Comment by komuw** [comment]
- an issue[1] was filed with `gobuffalo/uuid`    
- I sent a PR[2] to `gobuffalo/uuid`. after that was merged a version `v2.0.1` was released.
- after that release, I sent a PR[3] to `gomods/athens` to update to the just released uuid `v2.0.1`
- i do not know what happened to `v2.0.1` on  github
- but the athens mod file has a tag that exists[4]

1.  https://github.com/gobuffalo/uuid/issues/1
2. https://github.com/gobuffalo/uuid/pull/2
3. https://github.com/gomods/athens/pull/419/files
4. https://github.com/gomods/athens/blob/ea1503f0718789714645b4c8405b3b12d9550e63/go.mod#L20

**Comment by stanislas-m** [comment]
Thanks for the clues you found! I've restored the missing release. :)
